/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The signed-in user. The web client also probes it to learn whether another tab has
         *     already refreshed the session, before it spends the refresh token (ADR 0029).
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotates the refresh token. Presenting an already-rotated token means it was stolen
         *     (or replayed), so every session of that user is revoked.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_projects__project_id__api_keys_get"];
        put?: never;
        /** Create Api Key */
        post: operations["create_api_key_projects__project_id__api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Key */
        delete: operations["revoke_api_key_projects__project_id__api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_projects__project_id__agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_projects__project_id__agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_agents__agent_id__get"];
        /** Update Agent */
        put: operations["update_agent_agents__agent_id__put"];
        post?: never;
        /** Delete Agent */
        delete: operations["delete_agent_agents__agent_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Agent
         * @description One probe request against a saved agent's stored config, no retries.
         */
        post: operations["test_agent_agents__agent_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/agents/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Draft Agent
         * @description The same probe, for a not-yet-saved config (the add-agent form's "Test connection").
         *     The project id only scopes access; nothing about the draft is stored.
         */
        post: operations["test_draft_agent_projects__project_id__agents_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/suites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suites */
        get: operations["list_suites_projects__project_id__suites_get"];
        put?: never;
        /** Create Suite */
        post: operations["create_suite_projects__project_id__suites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suites/{suite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suite */
        get: operations["get_suite_suites__suite_id__get"];
        /** Update Suite */
        put: operations["update_suite_suites__suite_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suites/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Suite */
        post: operations["validate_suite_suites_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Results */
        get: operations["list_results_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{result_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_results__result_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description Per-case summaries (label, pass counts, consistency, latency, cost). Written when the
         *     run is summarized, so empty while it is still running.
         */
        get: operations["list_cases_runs__run_id__cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_runs_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suites/{suite_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_suites__suite_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Runs */
        get: operations["list_project_runs_projects__project_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stream-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Token */
        post: operations["stream_token_runs__run_id__stream_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run
         * @description `snapshot` (the run's state now), then `attempt` and `status` events until the run
         *     ends. Authenticated like any request, or with `?token=` from `POST
         *     /runs/{id}/stream-token` where the browser can't send the session cookie.
         */
        get: operations["stream_run_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run
         * @description A portable record of the run, recomputed from the persisted attempts via core's own
         *     `finalize_run` (ADR 0018): the strongest guarantee it agrees with core's statistics.
         *     `format=html` is one self-contained, fully escaped file (no external assets).
         */
        get: operations["export_run_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description Largest clusters (most failing attempts) first.
         */
        get: operations["list_findings_runs__run_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Baseline */
        post: operations["set_baseline_projects__project_id__baseline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Baselines
         * @description Every baseline in the project, for the overview's baseline indicator (ADR 0037).
         */
        get: operations["list_baselines_projects__project_id__baselines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/baselines/{branch}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Baseline
         * @description The baseline of suite `suite` (by name) for a registered `agent` (by name) or an
         *     unregistered `agent_name` on `branch`.
         */
        get: operations["get_baseline_projects__project_id__baselines__branch__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Verdict
         * @description This run against the baseline of its suite and agent on its branch (`main` for a run
         *     without one). 404 when no baseline is set there.
         */
        get: operations["run_verdict_runs__run_id__verdict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ci/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ci Report */
        post: operations["ci_report_ci_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Share */
        post: operations["create_share_runs__run_id__share_post"];
        /** Revoke Share */
        delete: operations["revoke_share_runs__run_id__share_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shared */
        get: operations["get_shared_shared__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Llm Config */
        get: operations["get_llm_config_config_llm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process answers. Touches nothing else.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: the database answers too. `commit` is the deployed commit, which the
         *     deploy workflow waits for (ADR 0036); None when the platform doesn't set it.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentIn */
        AgentIn: {
            /** Name */
            name: string;
            /** Config */
            config: components["schemas"]["HttpAgentConfig"] | components["schemas"]["McpAgentConfig"];
            auth_header?: components["schemas"]["AuthHeader"] | null;
        };
        /** AgentOut */
        AgentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Adapter Type */
            adapter_type: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Has Secret */
            has_secret: boolean;
        };
        /**
         * AgentResponse
         * @description One call to the agent under test. A failed call (after retries) has `error` set, an
         *     `ErrorStep` in `steps` and an empty `output`; adapters return it rather than raising.
         */
        AgentResponse: {
            /** Output */
            output: string;
            /** Steps */
            steps: (components["schemas"]["MessageStep"] | components["schemas"]["ToolCallStep"] | components["schemas"]["ToolResultStep"] | components["schemas"]["ErrorStep"])[];
            /** @default {} */
            usage: components["schemas"]["TokenUsage"];
            /** Latency Ms */
            latency_ms: number;
            /** Error */
            error?: string | null;
            /**
             * Tool Calls Reported
             * @default false
             */
            tool_calls_reported: boolean;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /**
         * AgentTestDraft
         * @description A not-yet-saved config, probed once and never persisted or logged (same validation as
         *     a real agent, since it's the same `AgentConfig`/`AuthHeader` types).
         */
        AgentTestDraft: {
            /** Config */
            config: components["schemas"]["HttpAgentConfig"] | components["schemas"]["McpAgentConfig"];
            auth_header?: components["schemas"]["AuthHeader"] | null;
        };
        /**
         * AgentTestOut
         * @description `message` is the adapter's own sanitized text: it never includes a resolved address
         *     (ADR 0012's SSRF guard keeps that out of user-facing errors) and is safe to show as-is.
         */
        AgentTestOut: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** AgentUpdate */
        AgentUpdate: {
            /** Name */
            name?: string | null;
            /** Config */
            config?: (components["schemas"]["HttpAgentConfig"] | components["schemas"]["McpAgentConfig"]) | null;
            auth_header?: components["schemas"]["AuthHeader"] | null;
            /**
             * Clear Secret
             * @default false
             */
            clear_secret: boolean;
        };
        /** ApiKeyCreated */
        ApiKeyCreated: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Last4 */
            last4: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Key */
            key: string;
        };
        /** ApiKeyIn */
        ApiKeyIn: {
            /** Label */
            label: string;
        };
        /** ApiKeyOut */
        ApiKeyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Last4 */
            last4: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** AttemptError */
        AttemptError: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "timeout" | "agent" | "unreachable" | "judge" | "budget" | "internal";
            /** Message */
            message: string;
        };
        /**
         * AttemptResult
         * @description One attempt of one case: the trace (`response`), every judge verdict and the
         *     accounting. `status` is `error` whenever `error` is set.
         */
        AttemptResult: {
            /** Case Id */
            case_id: string;
            /** Attempt */
            attempt: number;
            /** Input */
            input: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "error";
            response?: components["schemas"]["AgentResponse"] | null;
            /**
             * Judgments
             * @default []
             */
            judgments: components["schemas"]["JudgeResult"][];
            error?: components["schemas"]["AttemptError"] | null;
            /** Score */
            score?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Tokens */
            tokens?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Judge Cost Usd
             * @default 0
             */
            judge_cost_usd: number;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Ms */
            duration_ms: number;
        };
        /** AuthHeader */
        AuthHeader: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** BaselineIn */
        BaselineIn: {
            /** Branch */
            branch: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** BaselineOut */
        BaselineOut: {
            /** Branch */
            branch: string;
            /**
             * Suite Id
             * Format: uuid
             */
            suite_id: string;
            /** Agent Id */
            agent_id: string | null;
            /** Agent Name */
            agent_name: string | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            run: components["schemas"]["RunOut"];
        };
        /** CaseSummaryOut */
        CaseSummaryOut: {
            /** Case */
            case: string;
            /** Attack Category */
            attack_category: string | null;
            /** Label */
            label: string;
            /** Attempts */
            attempts: number;
            /** Passes */
            passes: number;
            /** Errors */
            errors: number;
            /** Pass Rate */
            pass_rate: number;
            /** Mean Score */
            mean_score: number | null;
            /** Consistency Score */
            consistency_score: number | null;
            /** Mean Latency Ms */
            mean_latency_ms: number | null;
            /** Total Cost */
            total_cost: number | null;
        };
        /** CiReportIn */
        CiReportIn: {
            /** Suite */
            suite: string;
            /** Agent */
            agent?: string | null;
            /** Agent Name */
            agent_name?: string | null;
            /** Results */
            results: components["schemas"]["AttemptResult"][];
            /** Runs Per Case */
            runs_per_case?: number | null;
            /**
             * Mock
             * @default true
             */
            mock: boolean;
            /** Model */
            model?: string | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Branch */
            branch: string;
            /** Pr Number */
            pr_number?: number | null;
            /** Baseline Branch */
            baseline_branch?: string | null;
        };
        /** CiReportOut */
        CiReportOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Verdict */
            verdict: string;
            /** Comparison */
            comparison: {
                [key: string]: unknown;
            } | null;
            /**
             * Top Findings
             * @default []
             */
            top_findings: components["schemas"]["TopFindingOut"][];
            /** Dashboard Url */
            dashboard_url: string | null;
        };
        /** CompareOut */
        CompareOut: {
            /**
             * Baseline Run Id
             * Format: uuid
             */
            baseline_run_id: string;
            /**
             * Candidate Run Id
             * Format: uuid
             */
            candidate_run_id: string;
            /** Report */
            report: {
                [key: string]: unknown;
            };
        };
        /** ErrorStep */
        ErrorStep: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** FindingOut */
        FindingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Cluster Label */
            cluster_label: string;
            /** Summary */
            summary: string;
            /** Suggested Fix */
            suggested_fix: string | null;
            /** Member Result Ids */
            member_result_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HttpAgentConfig
         * @description The HTTP adapter's own config (ADR 0012), so what's stored is what the adapter runs.
         */
        HttpAgentConfig: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /**
             * Method
             * @default POST
             * @enum {string}
             */
            method: "POST" | "PUT" | "PATCH";
            /** Headers */
            headers?: {
                [key: string]: string;
            };
            request_template?: components["schemas"]["JsonValue"];
            response?: components["schemas"]["ResponseMapping"];
            /**
             * Timeout Ms
             * @default 30000
             */
            timeout_ms: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
            /**
             * Follow Redirects
             * @default false
             */
            follow_redirects: boolean;
            /**
             * Allow Private
             * @default false
             */
            allow_private: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            adapter_type: "http";
        };
        JsonValue: unknown;
        /** JudgeResult */
        JudgeResult: {
            /** Judge */
            judge: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail" | "error";
            /** Score */
            score: number;
            /** Reason */
            reason: string;
            /**
             * Evidence
             * @default {}
             */
            evidence: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** JudgmentOut */
        JudgmentOut: {
            /** Judge */
            judge: string;
            /** Status */
            status: string;
            /** Score */
            score: number | null;
            /** Reason */
            reason: string | null;
        };
        /** LlmConfigOut */
        LlmConfigOut: {
            /** Provider */
            provider: string;
            /** Models */
            models: {
                [key: string]: string;
            };
        };
        /** Login */
        Login: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * McpAgentConfig
         * @description The MCP adapter's own HTTP-transport config (ADR 0023), so what's stored is what the
         *     adapter runs. `transport` is fixed to `"http"`: `McpHttpConfig` has no stdio fields at
         *     all, so a stored `transport: "stdio"` config is a plain 422, not a runtime check.
         */
        McpAgentConfig: {
            /**
             * Transport
             * @default http
             * @constant
             */
            transport: "http";
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Headers */
            headers?: {
                [key: string]: string;
            };
            /**
             * Timeout Ms
             * @default 30000
             */
            timeout_ms: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
            /**
             * Allow Private
             * @default false
             */
            allow_private: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            adapter_type: "mcp";
        };
        /** MessageStep */
        MessageStep: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message";
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ProjectIn */
        ProjectIn: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** Registration */
        Registration: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ResponseMapping
         * @description JSONPath expressions into the agent's JSON response.
         */
        ResponseMapping: {
            /**
             * Output
             * @default $.output
             */
            output: string;
            /** Tool Calls */
            tool_calls?: string | null;
            /**
             * Tool Name
             * @default $.tool
             */
            tool_name: string;
            /**
             * Tool Arguments
             * @default $.arguments
             */
            tool_arguments: string;
            /** Input Tokens */
            input_tokens?: string | null;
            /** Output Tokens */
            output_tokens?: string | null;
            /** Total Tokens */
            total_tokens?: string | null;
        };
        /** ResultOut */
        ResultOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Case */
            case: string;
            /** Attempt */
            attempt: number;
            /** Status */
            status: string;
            /** Label */
            label: string | null;
            /** Attack Category */
            attack_category: string | null;
            /** Output */
            output: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Tokens */
            tokens: number | null;
            /** Cost */
            cost: number | null;
            /** Error Kind */
            error_kind: string | null;
            /** Score */
            score: number | null;
            /** Judgments */
            judgments: components["schemas"]["JudgmentOut"][];
        };
        /**
         * RunDetailOut
         * @description A run for its own page: the suite's name, the agent's name as the run recorded it, and
         *     whether a share link is live (the link's token is only ever returned when it's created).
         */
        RunDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Suite Id
             * Format: uuid
             */
            suite_id: string;
            /** Suite Version */
            suite_version: number;
            /** Agent Id */
            agent_id: string | null;
            /** Agent Name */
            agent_name: string | null;
            /** Status */
            status: string;
            /** Model */
            model: string | null;
            /** Git Sha */
            git_sha: string | null;
            /** Branch */
            branch: string | null;
            /** Pr Number */
            pr_number: number | null;
            /** Runs Per Case */
            runs_per_case: number;
            /** Mock Mode */
            mock_mode: boolean;
            /** Attempts Total */
            attempts_total: number;
            /** Attempts Done */
            attempts_done: number;
            /** Pass Rate */
            pass_rate: number | null;
            /** Ci Lower */
            ci_lower: number | null;
            /** Ci Upper */
            ci_upper: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Total Cost */
            total_cost: number | null;
            /** Judge Cost Usd */
            judge_cost_usd: number | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Suite Name */
            suite_name: string;
            /** Agent */
            agent: string;
            /** Shared */
            shared: boolean;
            /** Share Expires At */
            share_expires_at: string | null;
        };
        /** RunIn */
        RunIn: {
            /** Runs Per Case */
            runs_per_case?: number | null;
            /** Model */
            model?: string | null;
            /**
             * Mock
             * @default true
             */
            mock: boolean;
            /** Git Sha */
            git_sha?: string | null;
            /** Branch */
            branch?: string | null;
            /** Pr Number */
            pr_number?: number | null;
        };
        /**
         * RunListOut
         * @description A run as shown in a project's run history (overview trends, latest-runs table).
         *     `agent_name` is the agent's current name for a registered agent, or the name an
         *     unregistered/CI-pushed run recorded for itself (ADR 0020) — whichever applies.
         *     `mean_latency_ms` isn't a stored column: it's the attempts-weighted average of
         *     `run_case_summaries.mean_latency_ms` across the run's cases, computed at read time.
         */
        RunListOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Suite Id
             * Format: uuid
             */
            suite_id: string;
            /** Suite Name */
            suite_name: string;
            /** Agent Id */
            agent_id: string | null;
            /** Agent Name */
            agent_name: string | null;
            /** Status */
            status: string;
            /** Branch */
            branch: string | null;
            /** Mock Mode */
            mock_mode: boolean;
            /** Pass Rate */
            pass_rate: number | null;
            /** Ci Lower */
            ci_lower: number | null;
            /** Ci Upper */
            ci_upper: number | null;
            /** Total Cost */
            total_cost: number | null;
            /** Judge Cost Usd */
            judge_cost_usd: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Mean Latency Ms */
            mean_latency_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Suite Id
             * Format: uuid
             */
            suite_id: string;
            /** Suite Version */
            suite_version: number;
            /** Agent Id */
            agent_id: string | null;
            /** Agent Name */
            agent_name: string | null;
            /** Status */
            status: string;
            /** Model */
            model: string | null;
            /** Git Sha */
            git_sha: string | null;
            /** Branch */
            branch: string | null;
            /** Pr Number */
            pr_number: number | null;
            /** Runs Per Case */
            runs_per_case: number;
            /** Mock Mode */
            mock_mode: boolean;
            /** Attempts Total */
            attempts_total: number;
            /** Attempts Done */
            attempts_done: number;
            /** Pass Rate */
            pass_rate: number | null;
            /** Ci Lower */
            ci_lower: number | null;
            /** Ci Upper */
            ci_upper: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Total Cost */
            total_cost: number | null;
            /** Judge Cost Usd */
            judge_cost_usd: number | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * RunVerdictOut
         * @description A run against its baseline: `report` is core's `RegressionReport`, None when the run
         *     is the baseline itself or hasn't completed yet.
         */
        RunVerdictOut: {
            /** Branch */
            branch: string;
            /**
             * Baseline Run Id
             * Format: uuid
             */
            baseline_run_id: string;
            /** Is Baseline */
            is_baseline: boolean;
            /** Report */
            report: {
                [key: string]: unknown;
            } | null;
        };
        /** ShareIn */
        ShareIn: {
            /** Expires In Days */
            expires_in_days?: number | null;
        };
        /** ShareOut */
        ShareOut: {
            /** Token */
            token: string;
            /** Url */
            url: string | null;
            /** Expires At */
            expires_at: string | null;
        };
        /** SharedCaseOut */
        SharedCaseOut: {
            /** Case */
            case: string;
            /** Label */
            label: string;
            /** Pass Rate */
            pass_rate: number;
            /** Passes */
            passes: number;
            /** Attempts */
            attempts: number;
        };
        /** SharedJudgmentOut */
        SharedJudgmentOut: {
            /** Judge */
            judge: string;
            /** Status */
            status: string;
            /** Reason */
            reason: string | null;
        };
        /** SharedResultOut */
        SharedResultOut: {
            /** Case */
            case: string;
            /** Attempt */
            attempt: number;
            /** Status */
            status: string;
            /** Output */
            output: string | null;
            /** Score */
            score: number | null;
            /** Error Kind */
            error_kind: string | null;
            /** Judgments */
            judgments: components["schemas"]["SharedJudgmentOut"][];
        };
        /** SharedRunOut */
        SharedRunOut: {
            /** Suite */
            suite: string;
            /** Agent */
            agent: string;
            /** Status */
            status: string;
            /** Runs Per Case */
            runs_per_case: number;
            /** Pass Rate */
            pass_rate: number | null;
            /** Ci Lower */
            ci_lower: number | null;
            /** Ci Upper */
            ci_upper: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Cases */
            cases: components["schemas"]["SharedCaseOut"][];
            /** Results */
            results: components["schemas"]["SharedResultOut"][];
        };
        /** StreamTokenOut */
        StreamTokenOut: {
            /** Token */
            token: string;
            /** Expires In */
            expires_in: number;
        };
        /** SuiteDetailOut */
        SuiteDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Case Count */
            case_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Yaml */
            yaml: string;
        };
        /** SuiteIn */
        SuiteIn: {
            /** Yaml */
            yaml: string;
        };
        /**
         * SuiteIssue
         * @description One problem in a suite YAML file. `line`/`col` (1-indexed) are set whenever a source
         *     position could be resolved: always for YAML syntax errors, best-effort for schema
         *     violations (located by walking the composed node tree against the error's field path).
         *     `path` is the dotted/bracketed pydantic field path, set only for schema violations.
         */
        SuiteIssue: {
            /** Message */
            message: string;
            /** Path */
            path?: string | null;
            /** Line */
            line?: number | null;
            /** Col */
            col?: number | null;
        };
        /** SuiteOut */
        SuiteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Case Count */
            case_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SuiteValidateOut */
        SuiteValidateOut: {
            /** Valid */
            valid: boolean;
            /** Case Count */
            case_count?: number | null;
            /** Issues */
            issues?: components["schemas"]["SuiteIssue"][];
        };
        /**
         * TokenUsage
         * @description The agent's own token usage, as it reports it. None: not reported.
         */
        TokenUsage: {
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /** ToolCallStep */
        ToolCallStep: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_call";
            /** Tool */
            tool: string;
            /** Arguments */
            arguments?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ToolResultStep */
        ToolResultStep: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_result";
            /** Tool */
            tool: string;
            result?: components["schemas"]["JsonValue"];
        };
        /** TopFindingOut */
        TopFindingOut: {
            /** Label */
            label: string;
            /** Summary */
            summary: string;
            /** Suggested Fix */
            suggested_fix: string | null;
            /** Member Count */
            member_count: number;
        };
        /** TraceJudgmentOut */
        TraceJudgmentOut: {
            /** Judge */
            judge: string;
            /** Status */
            status: string;
            /** Score */
            score: number | null;
            /** Reason */
            reason: string | null;
            /** Step */
            step: number | null;
        };
        /** TraceOut */
        TraceOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Case */
            case: string;
            /** Attempt */
            attempt: number;
            /** Status */
            status: string;
            /** Input */
            input: string;
            /** Output */
            output: string | null;
            /** Error */
            error: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Tokens */
            tokens: number | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Judge Cost Usd */
            judge_cost_usd: number;
            /** Retries */
            retries: number;
            /** Steps */
            steps: (components["schemas"]["MessageStep"] | components["schemas"]["ToolCallStep"] | components["schemas"]["ToolResultStep"] | components["schemas"]["ErrorStep"])[];
            /** Judgments */
            judgments: components["schemas"]["TraceJudgmentOut"][];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Registration"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_projects__project_id__api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_projects__project_id__api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_projects__project_id__api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_projects__project_id__agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_projects__project_id__agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_agents__agent_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_agent_agents__agent_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_draft_agent_projects__project_id__agents_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentTestDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suites_projects__project_id__suites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_suite_projects__project_id__suites_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuiteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suite_suites__suite_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_suite_suites__suite_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suite_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuiteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_suite_suites_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuiteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuiteValidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_results_runs__run_id__results_get: {
        parameters: {
            query?: {
                status?: string | null;
                label?: string | null;
                case?: string | null;
                attack_category?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_results__result_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_runs__run_id__cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_runs_compare_get: {
        parameters: {
            query: {
                a: string;
                b: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_suites__suite_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suite_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_runs_projects__project_id__runs_get: {
        parameters: {
            query?: {
                suite_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_token_runs__run_id__stream_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_runs__run_id__stream_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_runs__run_id__export_get: {
        parameters: {
            query?: {
                format?: "json" | "html";
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_runs__run_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_baseline_projects__project_id__baseline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BaselineIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_baselines_projects__project_id__baselines_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_baseline_projects__project_id__baselines__branch__get: {
        parameters: {
            query: {
                suite: string;
                agent?: string | null;
                agent_name?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
                branch: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_verdict_runs__run_id__verdict_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunVerdictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ci_report_ci_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CiReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CiReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_runs__run_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_share_runs__run_id__share_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shared_shared__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_config_config_llm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmConfigOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
